name: core_macos
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ macos-15 ]
    steps:
    - name: Deps (core)
      run: |
        brew update 
        brew install llvm libomp boost eigen assimp cmake
        echo "LLVM_PREFIX=$(brew --prefix llvm)" >> $GITHUB_ENV
        echo "HOMEBREW_PREFIX=$(brew --prefix)" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: rmagine

    - name: Configure
      run: |
        set -euxo pipefail
        mkdir -p rmagine/build
        cd rmagine/build

        # Put brewed LLVM first on PATH so `clang/clang++` resolve to it
        export PATH="${LLVM_PREFIX}/bin:${PATH}"

        # Use Homebrew LLVM's clang/clang++ (supports OpenMP out of the box).
        export CC=clang
        export CXX=clang++

        # Sanity check (helps diagnose path issues if it fails)
        which clang
        clang --version
        ls -l "$(which clang++)"

        cmake \
            -DCMAKE_PREFIX_PATH="${HOMEBREW_PREFIX};${LLVM_PREFIX}" \
            -DCMAKE_BUILD_TYPE=Release \
            -DRMAGINE_EMBREE_DISABLE=ON \
            -DRMAGINE_OUSTER_DISABLE=ON \
            -DRMAGINE_CUDA_DISABLE=ON \
            -DRMAGINE_OPTIX_DISABLE=ON \
            ..

    - name: Build
      working-directory: rmagine/build
      run: make -j"$(sysctl -n hw.logicalcpu)"

    - name: Test
      working-directory: rmagine/build
      run: |
        ./bin/rmagine_version
        ctest --output-on-failure