name: core-ubu22
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install APT Deps
      run: sudo apt install -y libboost-dev libeigen3-dev libassimp-dev
    - uses: threeal/cmake-action@v1.3.0
    - name: Build the project
      run: cmake --build build