name: core_macos
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ macos-15 ]
    steps:
    - name: Deps (core)
      run: |
        brew update 
        brew install libomp boost eigen assimp cmake
        echo "LLVM_PREFIX=$(brew --prefix llvm)" >> $GITHUB_ENV
        echo "HOMEBREW_PREFIX=$(brew --prefix)" >> $GITHUB_ENV
    - name: Clone
      uses: actions/checkout@v4
      with:
        path: rmagine
    - name: Configure
      working-directory: rmagine
      run: |
        mkdir build
        cd build

        # Use Homebrew LLVM's clang/clang++ (supports OpenMP out of the box).
        export CC="${LLVM_PREFIX}/bin/clang"
        export CXX="${LLVM_PREFIX}/bin/clang++"

        # Help CMake find Homebrew packages (Eigen, Boost, Assimp, libomp)
        cmake -DCMAKE_PREFIX_PATH="${HOMEBREW_PREFIX};${LLVM_PREFIX}" \
              -DCMAKE_C_COMPILER="$CC" \
              -DCMAKE_CXX_COMPILER="$CXX" \
              ..

    - name: Build
      working-directory: rmagine/build
      run: make -j"$(sysctl -n hw.logicalcpu)"

    - name: Test
      working-directory: rmagine/build
      run: |
        cd rmagine/build
        ./bin/rmagine_version
        ctest --output-on-failure