name: embree
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ macos-15 ]
    steps:
    - name: Deps (APT)
      run: sudo apt install -y libboost-dev libeigen3-dev libassimp-dev cmake
    - name: Clone
      uses: actions/checkout@v4
      with:
        path: rmagine
    - name: Compile
      run: |
        cd rmagine
        mkdir build
        cd build
        cmake ..
        make
    - name: Test
      run: |
        cd rmagine
        cd build
        ./bin/rmagine_version
        make test
