name: Rmagine Core - Ubuntu 20
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: threeal/cmake-action@v1.3.0
    - name: Install APT Deps
      run: sudo apt install -y libboost-dev
    - name: Test Output
      run: |
        echo "Hello Action!" >> $GITHUB_OUTPUT
    - name: Build the project
      run: cmake --build build